import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import Link from "next/link"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Weather Control</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Navbar/> */}
      <main className={styles.main}>
        
        <h1 className={styles.title}>
          Welcome to MCUweather
        </h1>

        <p className={styles.description}>
          A website all about weather data
        </p>
        <div className={styles.grid}>
          <a href="" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about our features and API.</p>
          </a>
          <Link href="/data">
            <a className={styles.card}>
              <h2>Data Table &rarr;</h2>
              <p>Take a look at the data table.</p>
            </a>
          </Link> 
          
          <Link href="/graphs">
            <a
              className={styles.card}
            >
              <h2>Graphs &rarr;</h2>
              <p>Discover graphs of weather data</p>
            </a>
          </Link>
          
        </div>
      </main>
    </div>
  )
}
